#!/bin/bash
echo $(echo "${WATER}" | tr 'ewatrhnsilcd' '0123456789' | sed 's/^0*//') + $(echo "${STIR}" | tr 'ewatrhnsilcd' '0123456789' | sed 's/^0*//') | bc | tr -d '\\' | tr '0123456789' 'sazntirfecl'

